services:
  - type: web
    name: videoinsight-ai      
    env: python
    runtime: python-3.11.0     
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: YOUTUBE_API_KEY   
        value: "${YOUTUBE_API_KEY}"
      - key: YT_COOKIES_PATH   
        value: "www.youtube.com_cookies.txt"


